package necro.livelier.pokemon.fabric.config;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public abstract class LivelierPokemonConfig {
    public static Map<String, Map<String,String>> createHashMap()
    {
        Map<String, Map<String,String>> newMap = new HashMap<String, Map<String,String>>()
        {{
            put("powerspot", new HashMap<String, String>(){{    put("trigger", "onSend");
                                                                put("type", "goal");
                                                                put("class", "OwnerEffectGoal");
                                                                put("parameter", "strength");}});
            put("friendguard", new HashMap<String, String>(){{  put("trigger", "onSend");
                                                                put("type", "goal");
                                                                put("class", "OwnerEffectGoal");
                                                                put("parameter", "resistance");}});
            put("serengrace", new HashMap<String, String>(){{   put("trigger", "onSend");
                                                                put("type", "goal");
                                                                put("class", "OwnerEffectGoal");
                                                                put("parameter", "luck");}});
            put("victorystar", new HashMap<String, String>(){{  put("trigger", "onSend");
                                                                put("type", "goal");
                                                                put("class", "OwnerEffectGoal");
                                                                put("parameter", "haste");}});
            put("healer", new HashMap<String, String>(){{       put("trigger", "onSend");
                                                                put("type", "goal");
                                                                put("class", "OwnerEffectGoal");
                                                                put("parameter", "clear");}});
            put("pastelveil", new HashMap<String, String>(){{   put("trigger", "onSend");
                                                                put("type", "goal");
                                                                put("class", "OwnerEffectGoal");
                                                                put("parameter", "clear");}});
            put("sweetveil", new HashMap<String, String>(){{    put("trigger", "onSend");
                                                                put("type", "goal");
                                                                put("class", "OwnerEffectGoal");
                                                                put("parameter", "clear");}});
            put("roughskin", new HashMap<String, String>(){{    put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "damage");}});
            put("ironbarbs", new HashMap<String, String>(){{    put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "damage");}});
            put("effectspore", new HashMap<String, String>(){{  put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "poison");}});
            put("poisonpoint", new HashMap<String, String>(){{  put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "poison");}});
            put("flamebody", new HashMap<String, String>(){{    put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "fire");}});
            put("cursedbody", new HashMap<String, String>(){{  put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "mining_fatigue");}});
            put("tanglinghair", new HashMap<String, String>(){{ put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "slowness");}});
            put("static", new HashMap<String, String>(){{       put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "slowness");}});
            put("gooey", new HashMap<String, String>(){{        put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "slowness");}});
            put("pressure", new HashMap<String, String>(){{     put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "durability");}});
            put("sandspit", new HashMap<String, String>(){{     put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "blindness");}});
            put("Kecleon", new HashMap<String, String>(){{      put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "hide");}});
            put("ballfetch", new HashMap<String, String>(){{    put("trigger", "onSend");
                                                                put("type", "goal");
                                                                put("class", "BallFetchGoal");
                                                                put("parameter", "");}});
            put("fire", new HashMap<String, String>(){{         put("trigger", "onSpawn");
                                                                put("type", "rain");
                                                                put("class", "EscapeRainGoal");
                                                                put("parameter", "1.0");}});
            put("Sudowoodo", new HashMap<String, String>(){{    put("trigger", "onSpawn");
                                                                put("type", "rain");
                                                                put("class", "EscapeRainGoal");
                                                                put("parameter", "0.75");}});
            put("Bonsly", new HashMap<String, String>(){{       put("trigger", "onSpawn");
                                                                put("type", "rain");
                                                                put("class", "EscapeRainGoal");
                                                                put("parameter", "0.75");}});
            put("perishbody", new HashMap<String, String>(){{   put("trigger", "onSpawn");
                                                                put("type", "revenge");
                                                                put("class", "PokemonRevengeGoal");
                                                                put("parameter", "wither");}});
            put("illuminate", new HashMap<String, String>(){{   put("trigger", "onSend");
                                                                put("type", "goal");
                                                                put("class", "EntityEffectGoal");
                                                                put("parameter", "glowing");}});
            put("tabletsofruin", new HashMap<String, String>(){{put("trigger", "onSpawn");
                                                                put("type", "goal");
                                                                put("class", "EntityEffectGoal");
                                                                put("parameter", "weakness");}});
            put("beadsofruin", new HashMap<String, String>(){{  put("trigger", "onSpawn");
                                                                put("type", "goal");
                                                                put("class", "EntityEffectGoal");
                                                                put("parameter", "weakness");}});
            put("swordofruin", new HashMap<String, String>(){{  put("trigger", "onSpawn");
                                                                put("type", "goal");
                                                                put("class", "EntityEffectGoal");
                                                                put("parameter", "weakness");}});
            put("vesselofruin", new HashMap<String, String>(){{ put("trigger", "onSpawn");
                                                                put("type", "goal");
                                                                put("class", "EntityEffectGoal");
                                                                put("parameter", "weakness");}});
            put("baddreams", new HashMap<String, String>(){{    put("trigger", "onSpawn");
                                                                put("type", "goal");
                                                                put("class", "PlayerSleepGoal");
                                                                put("parameter", "sleep");}});
            put("disguise", new HashMap<String, String>(){{     put("trigger", "onSpawn");
                                                                put("type", "effect");
                                                                put("class", "PokemonEffect");
                                                                put("parameter", "absorption");}});
            put("iceface", new HashMap<String, String>(){{      put("trigger", "onSpawn");
                                                                put("type", "effect");
                                                                put("class", "PokemonEffect");
                                                                put("parameter", "absorption");}});
            put("heatproof", new HashMap<String, String>(){{    put("trigger", "onSpawn");
                                                                put("type", "effect");
                                                                put("class", "PokemonEffect");
                                                                put("parameter", "fire_resistance");}});
            put("swiftswim", new HashMap<String, String>(){{    put("trigger", "onSpawn");
                                                                put("type", "effect");
                                                                put("class", "PokemonEffect");
                                                                put("parameter", "dolphins_grace");}});
            put("magnetpull", new HashMap<String, String>(){{   put("trigger", "onSend");
                                                                put("type", "goal");
                                                                put("class", "MagnetPullGoal");
                                                                put("parameter", "");}});
            put("Nosepass", new HashMap<String, String>(){{     put("trigger", "onSpawn");
                                                                put("type", "goal");
                                                                put("class", "NosepassGoal");
                                                                put("parameter", "");}});
            put("intrepidsword", new HashMap<String, String>(){{put("trigger", "onSpawn");
                                                                put("type", "effect");
                                                                put("class", "PokemonEffect");
                                                                put("parameter", "strength");}});
            put("intrepidshield", new HashMap<String, String>(){{put("trigger", "onSpawn");
                                                                put("type", "effect");
                                                                put("class", "PokemonEffect");
                                                                put("parameter", "strength");}});
            put("hugepower", new HashMap<String, String>(){{    put("trigger", "onSpawn");
                                                                put("type", "effect");
                                                                put("class", "PokemonEffect");
                                                                put("parameter", "strength");}});
            put("speedboost", new HashMap<String, String>(){{   put("trigger", "onSpawn");
                                                                put("type", "effect");
                                                                put("class", "PokemonEffect");
                                                                put("parameter", "speed");}});
            put("slowstart", new HashMap<String, String>(){{    put("trigger", "onSpawn");
                                                                put("type", "effect");
                                                                put("class", "PokemonEffect");
                                                                put("parameter", "slowstart");}});
        }};
        return newMap;
    }

    public static Set<String> createCatSet()
    {
        Set<String> newCatSet = new HashSet<String>()
        {{
            add("Meowth");
            add("Persian");
            add("Perrserker");
            add("Sprigatito");
            add("Floragato");
            add("Meowscarada");
            add("Skitty");
            add("Delcatty");
            add("Espeon");
            add("Shinx");
            add("Luxio");
            add("Luxray");
            add("Raikou");
            add("Zeraora");
            add("Glameow");
            add("Purugly");
            add("Liepard");
            add("Purrloin");
            add("Litleo");
            add("Pyroar");
            add("Litten");
            add("Torracat");
            add("Incineroar");
            add("Espurr");
            add("Meowstic");
            add("Solgaleo");
        }};
        return newCatSet;
    }
}
